### ISSUE TITLE
add real data table titles and descriptions

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-chl-transect-underway-discrete#8]
Current titles and descriptions are placeholders, assigning this to you @sbeaulieu as you may have ideas about what to put in these metadata fields.

**Comment by sbeaulieu** [comment]
chl-transect-underway-discrete.csv
    NES-LTER underway discrete chlorophyll data
    Underway discrete chlorophyll data during NES-LTER Transect cruises

chl-transect-underway-post-cal.csv
    NES-LTER post-calibrated underway fluorometer data
    Post-calibrated underway fluorometer data during NES-LTER Transect cruises

**Comment by joefutrelle** [comment]
@sbeaulieu feel free to kick this back to me if you'd like me to make these updates.
